version: '3.8'
services:
  database:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai-notes
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://172.20.0.2:5432/ai-notes
  #      SPRING_DATASOURCE_USERNAME: admin
  #      SPRING_DATASOURCE_PASSWORD: password
  #      SPRING_PROFILES_ACTIVE: docker
  #    env_file:
  #      - dev.env
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      database:
  #        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - database
volumes:
  db-data: